config/routes.rb
Rails.application.routes.draw do

  resources :reports

  resources :product_data

  resources :users, :only => :show do
    member do
      get 'download'
    end
  end

  resources :report_entries do
    member do
      get 'download'
    end
  end

end

app/models/csv_report.rb
class CsvReport < ActiveRecord::Base
  has_attached_file :report_file
  validates_attachment :report_file, :presence => true, 
  :content_type => { :content_type => 'text/csv' }
end

app/models/outlet.rb
class Outlet < ActiveRecord::Base
  has_paper_trail
end

app/models/product_data.rb
class ProductData < ActiveRecord::Base
  belongs_to :csv_report
  validates :product_name, :product_type, :quantity, :throwaway, :price, :branch, :csv_report, :presence => true
end

app/models/report_entry.rb
class ReportEntry < ActiveRecord::Base
  belongs_to :outlet
  belongs_to :shift
  belongs_to :user
  has_paper_trail
end

app/models/shift.rb
class Shift < ActiveRecord::Base
  has_paper_trail
end

app/models/user.rb
class User < ActiveRecord::Base
  has_paper_trail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/product_data_controller.rb
class ProductDataController < ApplicationController
  def index
    @products = ProductData.all
  end
end

app/controllers/report_entries_controller.rb
class ReportEntriesController < ApplicationController
  def show
    @entry = ReportEntry.find(params[:id])
    @start_date = Date.today
    @end_date = @start_date + 1.month
    respond_to do |format|
      # format.pdf { send_file TestPdfForm.new(@user).export, type: 'application/pdf' }
      format.pdf do
        render :pdf => 'SALES_REPORT', 
               :orientation => 'Portrait', 
               :show_as_html => params[:debug].present?
      end
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def new
    @report = CsvReport.new
  end

  def create
    csv_entries = SmarterCSV.process(params[:csv_report][:report_file].tempfile)
    # parses each entry of the data and saves it to the database
    @report = CsvReport.create(:json_data => csv_entries.to_json, 
      :report_file => params[:csv_report][:report_file])
    csv_entries.each_with_index do |data, i|
      line_number = i + 1
      p = ProductData.create(:product_name => data[:product_name], 
        :product_type => data[:product_type], 
        :quantity => data[:quantity], 
        :throwaway => data[:throwaway], 
        :price => data[:price], 
        :branch => data[:branch], 
        :csv_report => @report)
      if p.errors.any?
        @report.errors[line_number.to_s] = p.errors
      end
    end

    if @report.errors.any?
      render 'new'
    else
      redirect_to product_data_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      # format.pdf { send_file TestPdfForm.new(@user).export, type: 'application/pdf' }
      format.pdf do
        render :pdf => 'user', 
               :orientation => 'Landscape', 
               :save_to_file => Rails.root.join('pdfs', "#{@user.last_name}, #{@user.first_name}.pdf")
      end
    end
  end

  def download
    @user = User.find(params[:id])
    html = render_to_string(:template => 'users/show.pdf.haml', :locals => { :user =>@user })
    pdf = WickedPdf.new.pdf_from_string(html, :orientation => 'Landscape')
    send_data(pdf, 
    :filename    => "my_pdf_name.pdf", 
    :disposition => 'attachment')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_data_helper.rb
module ProductDataHelper
end

app/helpers/report_entries_helper.rb
module ReportEntriesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReportsGenerationPoc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/product_data/index.html.haml
%table.table.table-striped
  %thead
    %tr 
      %td Product Name
      %td Product Type
      %td Quantity
      %td Throwaway
      %td Price
      %td Branch
  %tbody
    - @products.each do |product|
      %tr
        %td #{product.product_name}
        %td #{product.product_type}
        %td #{product.quantity}
        %td #{product.throwaway}
        %td #{product.price}
        %td #{product.branch}

app/views/report_entries/show.pdf.haml
/ = stylesheet_link_tag "bootstrap_and_overrides"
= wicked_pdf_stylesheet_link_tag "bootstrap_and_overrides"
.container-fluid
  .row-fluid
    TRIVISION VENTURES INC.
    %br
    Summary of Shortages
    %br
    From #{@start_date} to #{@end_date}

  .row-fluid
    %p
      Below please find summary of shortages from December 01 to 31 to be checked by the personnel concerned. This is to reconciled on February 10 (Monday) and please be inforned that only documented sales report will be honored. Failure to comply as for specified date will mean accepting the said shortages. Please take note that all shortages will be deducted on February 25 payroll as is (one deduction only) regardless of the amount.

  .row-fluid
    %table.table.table-bordered
      %thead
        %tr
          %th OUTLET
          %th SHIFT
          %th DATE
          %th NAME
          %th TOTAL SALES
          %th CASH REMITTED
          %th SHORT
          %th REMARKS
      %tbody
        %tr
          %td #{@entry.outlet.name}
          %td #{@entry.shift.number}
          %td #{Date.today}
          %td #{@entry.user.last_name} #{@entry.user.first_name}
          %td #{@entry.total_sales}
          %td #{@entry.cash_remitted}
          %td #{@entry.short}
          %td #{@entry.remarks}
      

app/views/reports/new.html.haml
= simple_form_for @report , :url => reports_path, :html => {:multipart => true}, :method => :post do |f|
  - if @report.errors.any?
    #error_explanation
      %ul
        - @report.errors.each do |k,v|
          %h5
            Row #{k} Errors
          - v.full_messages.each do |msg|
            %li= msg
  = f.input :report_file, :as => :file
  = f.button :submit

app/views/users/show.pdf.haml
%h1 Testing HTML to PDF

%h3 First Name
#{@user.first_name}
%h3 Last Name
#{@user.last_name}
%h3 Address
#{@user.address}
%h3 Address_2
#{@user.address_2}
%h3 State
#{@user.state}
%h3 Zip code
#{@user.zip_code}
%h3 Age
#{@user.age}


/ %table
/   - (1..20).each do |r|
/     %tr
/       - (1..40).each do |ch|
/         %th
/           = "Hello #{ch}"
/     %tr
/       - (1..40).each do |cd|
/         %td 
/           = "Hello #{cd}"